version: '3.4'

services:
  testsignalr:
    image: 01686120288/test-signalr:dev
    container_name: TestSignalR
    build:
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "TestSignalR"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_testsignalr$
    volumes:
      - E:\MISA\TestSignalR\TestSignalR:/app
      - E:\MISA\TestSignalR:/src
      - C:\Users\duong\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_testsignalr$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_testsignalr$ \"/app/bin/Release/net5.0/TestSignalR.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true